// This file is auto-generated by the Supabase CLI.
// Run the following command to regenerate it against the live project schema:
//
//   supabase gen types typescript --project-id <your-project-id> > src/types/database.types.ts
//
// Do NOT manually edit the generated types below this comment.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<
      string,
      {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      }
    >;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
