ALTER TABLE events RENAME COLUMN date TO start_date;
ALTER TABLE events ADD COLUMN end_date TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN status TEXT NOT NULL DEFAULT 'upcoming';
ALTER TABLE events ADD COLUMN type TEXT NOT NULL;
